"""add_player_global_stats

Revision ID: 002
Revises: 001
Create Date: 2025-12-03 14:53:27.358084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '002'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Make migration idempotent - check if table exists before creating
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    tables = inspector.get_table_names()
    
    # Create player_global_stats table if it doesn't exist
    if 'player_global_stats' not in tables:
        try:
            op.create_table(
                'player_global_stats',
                sa.Column('player_id', sa.Integer(), nullable=False),
                sa.Column('current_rating', sa.Float(), nullable=False, server_default='1200.0'),
                sa.Column('total_games', sa.Integer(), nullable=False, server_default='0'),
                sa.Column('total_wins', sa.Integer(), nullable=False, server_default='0'),
                sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
                sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
                sa.PrimaryKeyConstraint('player_id')
            )
        except Exception as e:
            # Table might have been created between check and create
            if 'already exists' not in str(e).lower() and 'duplicate' not in str(e).lower():
                raise
    
    # Create index if table exists and index doesn't
    if 'player_global_stats' in tables:
        try:
            indexes = [idx['name'] for idx in inspector.get_indexes('player_global_stats')]
            if 'idx_player_global_stats_player' not in indexes:
                op.create_index('idx_player_global_stats_player', 'player_global_stats', ['player_id'], unique=False)
        except Exception:
            pass  # Index might already exist
    
    # Create unique constraint on signup_players if table exists
    if 'signup_players' in tables:
        try:
            unique_constraints = inspector.get_unique_constraints('signup_players')
            # Check if unique constraint on (signup_id, player_id) exists
            has_constraint = any(
                set(c['column_names']) == {'signup_id', 'player_id'}
                for c in unique_constraints
            )
            if not has_constraint:
                op.create_unique_constraint('uq_signup_players_signup_player', 'signup_players', ['signup_id', 'player_id'])
        except Exception:
            pass  # Constraint might already exist
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'signup_players', type_='unique')
    op.drop_index('idx_player_global_stats_player', table_name='player_global_stats')
    op.drop_table('player_global_stats')
    # ### end Alembic commands ###
