"""add_player_global_stats

Revision ID: 002
Revises: 001
Create Date: 2025-12-03 14:53:27.358084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '002'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'player_global_stats',
        sa.Column('player_id', sa.Integer(), nullable=False),
        sa.Column('current_rating', sa.Float(), nullable=False, server_default='1200.0'),
        sa.Column('total_games', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('total_wins', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
        sa.PrimaryKeyConstraint('player_id')
    )
    op.create_index('idx_player_global_stats_player', 'player_global_stats', ['player_id'], unique=False)
    op.create_unique_constraint(None, 'signup_players', ['signup_id', 'player_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'signup_players', type_='unique')
    op.drop_index('idx_player_global_stats_player', table_name='player_global_stats')
    op.drop_table('player_global_stats')
    # ### end Alembic commands ###



